version: "3.9"

services:
  db:
    image: postgres:13.0-alpine
    container_name: "ftp-db"
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres

  web:
    build: .
    container_name: "ftp-web"
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
        - .:/usr/src/app/
    ports:
      - "8000:8000"
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

volumes:
    postgres_data:
